kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: composer
    commands:
      - composer install

  - name: lint
    image: php:7.4-alpine
    commands:
      - vendor/bin/phpcs
      - vendor/bin/psalm

  - name: test
    image: php:7.4-alpine
    commands:
      - vendor/bin/phpunit
